version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: lti_postgres
    environment:
      POSTGRES_USER: LTIdbUser
      POSTGRES_PASSWORD: D1ymf8wyQEGthFR1E9xhCq
      POSTGRES_DB: LTIdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
